### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by heavy7** [ray-x/nvim#6]
How to install on windows?

**Comment by ray-x** [comment]
I presume most of the settings are already there. Major concern is the path setup for windows is not the same. But I do not have a windows machine to verify.

**Comment by ray-x** [comment]
I made some changes and hope it works

**Comment by heavy7** [comment]
The old error disappeared, but a new one appeared
![image](https://user-images.githubusercontent.com/37082495/137589866-e8b05f6a-592e-4847-b578-8b8d6b45535d.png)

**Comment by ray-x** [comment]
That was used to setup lua. It should be fixed

**Comment by manish-o** [comment]
Facing this issue in windows while installing

![image](https://user-images.githubusercontent.com/80611918/218252477-77d39c92-51f6-4150-9254-d9f3480d7be7.png)

**Comment by ray-x** [comment]
It may not necessary releated to path. 
Looking int option:152  There may be an option that failed to be set. Are you with latest neovim? could you also check if neovim nightly works for you?

**Comment by Felopater-Melika** [comment]
I had that same issue in the last screenshot and tried the nightly version and i am getting this: 
![image](https://user-images.githubusercontent.com/68111601/220444417-c53900f3-24d3-4275-ae92-391e5d77dfea.png)
I also tried it on wsl arch linux and getting the same error

**Comment by ray-x** [comment]
Pushed a fix for it. May relate to migration to lazy.

**Comment by Felopater-Melika** [comment]
it installed correctly this time but setup didn't go well apparently also i think there are some errors related to using kitty and that's not possible on windows unfortunately 
![image](https://user-images.githubusercontent.com/68111601/220670479-f70ce4a6-f7d3-4778-a9c6-105c3095f9ad.png)
![image](https://user-images.githubusercontent.com/68111601/220670590-a8d67982-3c2b-451e-a9e4-ff536acc1e55.png)

**Comment by ray-x** [comment]
ok, this is something related to lazy setup option. it should be fixed in my other push: f0b4fb86419d415e52dae23089c90cf3ee620bfb

**Comment by Felopater-Melika** [comment]
now I have all these errors when I start nvim
![image](https://user-images.githubusercontent.com/68111601/220823781-9547bb25-6193-4a36-a9f6-6bb549b48584.png)
![image](https://user-images.githubusercontent.com/68111601/220823808-761cca4d-8834-4a3f-8664-c4a0f98b4045.png)
![image](https://user-images.githubusercontent.com/68111601/220823817-4cb94bc5-eecc-4ab1-a4b4-fdf45ac031dc.png)
![image](https://user-images.githubusercontent.com/68111601/220823842-e6e3447c-3f0a-4cb7-be76-03d39d2b3a65.png)
![image](https://user-images.githubusercontent.com/68111601/220823866-7e9881bb-f7af-4704-a4c8-c971551fe1d5.png)
![image](https://user-images.githubusercontent.com/68111601/220823887-3b469917-081a-4b61-8c58-453db7d65cd5.png)
when I also type : this happens
![image](https://user-images.githubusercontent.com/68111601/220824025-922d1902-78b6-47b9-ac6a-075baa6c9165.png)
![image](https://user-images.githubusercontent.com/68111601/220824203-f0e777a4-c4ff-4f31-92b1-cfa98d0dcd83.png)

**Comment by ray-x** [comment]
Looks to me none of the plugins was install. Did you see Lazy setup screen when you start nvim first time.

Also are you using WSL, or windows cmd line or mingw/git-prompt ?

**Comment by Felopater-Melika** [comment]
it works fine now only weird issue is theme changes from time to time lol and that the bar says i am using BSD LOL
and this small error 
![image](https://user-images.githubusercontent.com/68111601/220982568-cecf02ed-fe01-45a1-b8e4-0c0d0bd8c297.png)

**Comment by ray-x** [comment]
Ok.
For the wilder_python error, you need to setup your vim.g.python3_host_prog and `UpdateRemotePlugings` Please check wilder setup
https://github.com/gelguy/wilder.nvim

Regarding loading the spinner, it is something I am working on. I disabled in my last commits.
The colorscheme setup is here:
https://github.com/ray-x/nvim/blob/537d090e286c169d6a9a15d5553f0b9803224206/lua/core/colorscheme.lua#L31
You can remove the colorschemes you do not need from the list.

**Comment by Felopater-Melika** [comment]
I updated the vim.g.python3_host_prog and trying to update remote plugins but nvim no longer opening lua files after this showed 
![image](https://user-images.githubusercontent.com/68111601/221270685-f06154b1-fcea-4bd3-bad6-7894ecfe436a.png)

it just opens for a second then instantly closes

**Comment by ray-x** [comment]
I pushed another commit, please check if it works. Also if you setup HOME env?

**Comment by Felopater-Melika** [comment]
HOME env?

also the error still persists I don't know if this is the cause 
![image](https://user-images.githubusercontent.com/68111601/221330235-fc1d137a-c02f-4699-ab9d-cd7557b0c2ac.png)

but usually it either closes or opens and just lags
![image](https://user-images.githubusercontent.com/68111601/221330252-072bd239-44d9-4580-b113-b23bc473837a.png)

**Comment by ray-x** [comment]
In the first screen. Those 3 plugins may not run correctly in windows. You can remove it from the list.

Once those plugins removed, please restart the nvim and run `:Lazy`. What is the output?
Also what is the output of `:checkhealth`.  Are there any outstanding issues?
